builders:
  copy_with:
    import: 'package:generators/builder.dart'
    builder_factories:
      - copyWithGenerator
    build_extensions:
      .dart:
      - copy_with.g.part
    auto_apply: dependents
    build_to: cache
    applies_builders:
      - source_gen|combining_builder

  json:
    import: 'package:generators/builder.dart'
    builder_factories:
      - jsonGenerator
    build_extensions:
      .dart:
      - .j.dart
    auto_apply: dependents
    build_to: source
    runs_before:
      - json_serializable|json_serializable