name: generators
description: Code generators to demonstrate usage of different builders provided by source_gen.
version: 1.0.0
author: Sarbagya Dhaubanjar

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  analyzer: 0.39.11
  build: 1.2.1
  build_resolvers: 1.2.2
  source_gen: ^0.9.7+1

dev_dependencies:
  pedantic: ^1.9.0